import type { Metadata } from "next";
import "./globals.css";
import {RegisterProvider} from "@/app/(_portal)/_context/RegisterContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col justify-center`}
      >
          <RegisterProvider>
              <div className="flex-1 flex items-center justify-center">
                  {children}
              </div>
          </RegisterProvider>
      </body>
    </html>
  );
}
